#!/usr/bin/env python3
"""Build tooling for Extreme Anglin' Atlas fishing data."""

from __future__ import annotations

import argparse
import csv
import io
import json
import re
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WOWWIKI = ROOT / "data" / "fishing_locations_wikitext.json"
DEFAULT_GENERATED_CSV = ROOT / "data" / "generated" / "fishing_locations_wowwiki.csv"
DEFAULT_MANUAL_CSV = ROOT / "data" / "manual" / "fishing_entries.csv"
DEFAULT_FISH_DIR = ROOT / "data" / "manual" / "fish"
DEFAULT_ZONE_DIR = ROOT / "data" / "manual" / "zones"
DEFAULT_JSON = ROOT / "addon" / "Data" / "FishingData.json"
DEFAULT_LUA = ROOT / "addon" / "Data" / "FishingData.lua"

WOWWIKI_PHASE = "tbc"
WOWWIKI_SECTION_EXPANSIONS = {
    "Eastern Kingdoms Zones": "classic",
    "Kalimdor Zones": "classic",
    "Outland Zones": "tbc",
}
WOWWIKI_ITEM_NAME_FIXES = {
    "Greater Sagefish": "Raw Greater Sagefish",
    "Raw Mithril Headed Trout": "Raw Mithril Head Trout",
}
ZONE_NAME_ALIASES = {
    "Barrens": "The Barrens",
    "Deadmines": "The Deadmines",
    "Hinterlands": "The Hinterlands",
    "Tirisfal Glades": "Tirisfal Glade",
    "Un'Goro Crater": "Un'goro Crater",
}
ZONE_CATEGORY_ORDER = {
    "Eastern Kingdoms": 0,
    "Kalimdor": 1,
    "Outland": 2,
    "Other": 3,
}
CSV_COLUMNS = [
    "zone_name",
    "zone_external_id",
    "zone_category",
    "expansion",
    "item_id",
    "item_name",
    "min_skill",
    "max_skill",
    "phase",
    "source_label",
    "source_url",
    "notes",
]


class DataError(ValueError):
    pass


def extract_wowwiki(args: argparse.Namespace) -> None:
    wikitext = read_wowwiki_wikitext(args.input)
    item_ids = read_fish_item_ids(args.fish_dir)
    zone_metadata = read_zone_metadata(args.zone_dir)
    rows = collapse_rows(list(extract_wowwiki_rows(wikitext, item_ids, zone_metadata)))

    write_csv(args.out, rows)

    print(f"Loaded {len(item_ids)} fish item IDs from {args.fish_dir}")
    print(f"Loaded {len(zone_metadata)} zone metadata records from {args.zone_dir}")
    print(f"Extracted {len(rows)} fishing rows into {args.out}")


def export_json(args: argparse.Namespace) -> None:
    payload = build_payload(args.csv)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Exported {args.out}")


def export_lua(args: argparse.Namespace) -> None:
    payload = build_payload(args.csv)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        "-- Generated by scripts/extremeanglinatlas_data.py. Do not edit by hand.\n"
        f"{args.global_name} = {to_lua(payload)}\n",
        encoding="utf-8",
    )
    print(f"Exported {args.out}")


def build_payload(csv_paths: list[Path]) -> dict[str, object]:
    rows = collapse_rows(
        [
            normalize_row(row_number, row)
            for path in csv_paths
            for row_number, row in read_csv(path)
        ]
    )
    zones = build_zones(rows)

    return {
        "meta": {
            "schemaVersion": 1,
            "generatedFrom": "csv",
        },
        "items": build_items(rows),
        "zones": zones,
    }


def build_items(rows: list[dict[str, str]]) -> list[dict[str, object]]:
    items: dict[str, dict[str, object]] = {}
    for row in rows:
        key = row["item_id"] or row["item_name"]
        item = items.setdefault(
            key,
            {
                "name": row["item_name"],
                "category": "fish",
            },
        )
        if row["item_id"]:
            item["itemId"] = int(row["item_id"])

    return sorted(items.values(), key=lambda item: str(item["name"]))


def build_zones(rows: list[dict[str, str]]) -> list[dict[str, object]]:
    zones_by_name: dict[str, dict[str, object]] = {}
    fish_by_zone: dict[str, list[dict[str, object]]] = {}

    for row in rows:
        zones_by_name[row["zone_name"]] = {
            "name": row["zone_name"],
            "externalId": optional_export_int(row["zone_external_id"]),
            "category": row["zone_category"],
            "expansion": row["expansion"],
        }
        fish_by_zone.setdefault(row["zone_name"], []).append(build_fish(row))

    zones = [
        without_none(
            {
                "id": index,
                **zone,
                "fish": sorted(
                    fish_by_zone[zone["name"]],
                    key=lambda fish: str(fish["itemName"]),
                ),
            }
        )
        for index, zone in enumerate(sorted(zones_by_name.values(), key=zone_sort_key), start=1)
    ]
    return zones


def build_fish(row: dict[str, str]) -> dict[str, object]:
    source = without_none(
        {
            "label": nonempty(row["source_label"]),
            "url": nonempty(row["source_url"]),
        }
    )
    return without_none(
        {
            "itemId": optional_export_int(row["item_id"]),
            "itemName": row["item_name"],
            "minSkill": optional_export_int(row["min_skill"]),
            "maxSkill": optional_export_int(row["max_skill"]),
            "phase": row["phase"],
            "notes": nonempty(row["notes"]),
            "sources": [source] if source else [],
        }
    )


def zone_sort_key(zone: dict[str, object]) -> tuple[int, str]:
    category = str(zone["category"])
    return (ZONE_CATEGORY_ORDER.get(category, ZONE_CATEGORY_ORDER["Other"]), str(zone["name"]))


def read_csv(path: Path) -> Iterable[tuple[int, dict[str, str]]]:
    if not path.exists():
        raise DataError(f"CSV file does not exist: {path}")

    raw_lines = path.read_text(encoding="utf-8").splitlines()
    lines = [
        line
        for line in raw_lines
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if not lines:
        return []

    reader = csv.DictReader(io.StringIO("\n".join(lines)))
    missing = [column for column in CSV_COLUMNS if column not in (reader.fieldnames or [])]
    if missing:
        raise DataError(f"{path} is missing columns: {', '.join(missing)}")

    for row_number, row in enumerate(reader, start=2):
        yield row_number, {key: (value or "").strip() for key, value in row.items()}


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as output:
        writer = csv.DictWriter(output, fieldnames=CSV_COLUMNS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def normalize_row(row_number: int, row: dict[str, str]) -> dict[str, str]:
    normalized = {column: row.get(column, "").strip() for column in CSV_COLUMNS}
    required_text(row_number, normalized, "zone_name")
    required_text(row_number, normalized, "item_name")
    optional_int(row_number, normalized, "zone_external_id")
    optional_int(row_number, normalized, "item_id")
    optional_int(row_number, normalized, "min_skill")
    optional_int(row_number, normalized, "max_skill")

    normalized["zone_category"] = normalized["zone_category"] or "Other"
    normalized["expansion"] = normalized["expansion"] or "tbc"
    normalized["phase"] = normalized["phase"] or "tbc"
    normalized["source_label"] = normalized["source_label"] or "wowhead"
    return normalized


def required_text(row_number: int, row: dict[str, str], column: str) -> str:
    value = row.get(column, "").strip()
    if not value:
        raise DataError(f"Row {row_number}: {column} is required")
    return value


def optional_int(row_number: int, row: dict[str, str], column: str) -> int | None:
    value = row.get(column, "").strip()
    if not value:
        return None
    try:
        return int(value)
    except ValueError as exc:
        raise DataError(f"Row {row_number}: {column} must be an integer") from exc


def optional_export_int(value: str) -> int | None:
    return int(value) if value else None


def collapse_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    collapsed: dict[tuple[str, str, str], dict[str, str]] = {}
    for row in rows:
        key = (row["zone_name"], row["item_name"], row["phase"])
        existing = collapsed.get(key)
        if not existing:
            collapsed[key] = dict(row)
            continue

        existing.update({key: value for key, value in row.items() if value})
        existing["min_skill"] = lowest_skill(existing["min_skill"], row["min_skill"])
        existing["max_skill"] = lowest_skill(existing["max_skill"], row["max_skill"])

    return list(collapsed.values())


def lowest_skill(left: str, right: str) -> str:
    if not left:
        return right
    if not right:
        return left
    return str(min(int(left), int(right)))


def read_wowwiki_wikitext(path: Path) -> str:
    payload = json.loads(path.read_text(encoding="utf-8"))
    try:
        return str(payload["parse"]["wikitext"]["*"])
    except KeyError as exc:
        raise DataError(f"{path} does not look like a MediaWiki parse response") from exc


def read_fish_item_ids(fish_dir: Path) -> dict[str, int]:
    item_ids: dict[str, int] = {}
    for path in sorted(fish_dir.glob("*.out")):
        if path.name.startswith("error_"):
            continue

        title, wikitext = read_parse_response(path)
        match = re.search(r"\{\{\s*elinks-item\s*\|\s*(\d+)", wikitext, re.IGNORECASE)
        if not match:
            raise DataError(f"{path} is missing an elinks-item item ID")

        item_ids[title] = int(match.group(1))

    return item_ids


def read_zone_metadata(zone_dir: Path) -> dict[str, dict[str, object]]:
    zone_metadata: dict[str, dict[str, object]] = {}
    for path in sorted(zone_dir.glob("*.out")):
        if path.name.startswith("error_"):
            continue

        title, wikitext = read_parse_response(path)
        zone_name = ZONE_NAME_ALIASES.get(title, title)
        match = re.search(r"\{\{\s*elinks-zone\s*\|\s*(\d+)", wikitext, re.IGNORECASE)
        if not match:
            continue

        zone_metadata[zone_name] = {
            "external_id": int(match.group(1)),
            "category": read_zone_category(wikitext),
        }

    return zone_metadata


def read_parse_response(path: Path) -> tuple[str, str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    try:
        return str(payload["parse"]["title"]), str(payload["parse"]["wikitext"]["*"])
    except KeyError as exc:
        raise DataError(f"{path} does not look like a MediaWiki parse response") from exc


def read_zone_category(wikitext: str) -> str:
    for template in re.findall(r"\{\{\s*(Eastern Kingdoms|Kalimdor|Outland)\s*\}\}", wikitext, re.IGNORECASE):
        return clean_wiki_text(template)

    for category in re.findall(r"\[\[\s*Category\s*:\s*([^\]|]+)", wikitext, re.IGNORECASE):
        cleaned = clean_wiki_text(category)
        if cleaned in ZONE_CATEGORY_ORDER:
            return cleaned
        if cleaned in {"Eastern Kingdoms zones", "Kalimdor zones", "Outland zones"}:
            return cleaned.replace(" zones", "")

    return "Other"


def extract_wowwiki_rows(
    wikitext: str,
    item_ids: dict[str, int],
    zone_metadata: dict[str, dict[str, object]],
) -> Iterable[dict[str, str]]:
    for section_name, section_text in iter_wowwiki_sections(wikitext):
        expansion = WOWWIKI_SECTION_EXPANSIONS.get(section_name)
        if not expansion:
            continue

        section_category = section_name.replace(" Zones", "")
        for cells in iter_wiki_table_rows(section_text):
            if len(cells) > 5 and all(not cell.strip() for cell in cells[5:]):
                cells = cells[:5]
            if len(cells) != 5:
                continue

            zone, _location, min_skill, max_skill, fish_text = cells
            zone_name = clean_wiki_text(zone)
            zone_info = zone_metadata.get(zone_name, {})
            zone_category = str(zone_info.get("category") or section_category or "Other")
            if zone_category == "Other":
                zone_category = section_category or "Other"

            for item_name in extract_item_names(fish_text):
                item_id = str(item_ids.get(item_name, ""))
                yield {
                    "zone_name": zone_name,
                    "zone_external_id": str(zone_info.get("external_id", "")),
                    "zone_category": zone_category,
                    "expansion": expansion,
                    "item_id": item_id,
                    "item_name": item_name,
                    "min_skill": clean_skill(min_skill),
                    "max_skill": clean_skill(max_skill),
                    "phase": WOWWIKI_PHASE,
                    "source_label": "wowhead",
                    "source_url": f"https://www.wowhead.com/classic/item={item_id}" if item_id else "",
                    "notes": "",
                }


def iter_wowwiki_sections(wikitext: str) -> Iterable[tuple[str, str]]:
    heading_pattern = re.compile(r"^===\s*(.*?)\s*===$", re.MULTILINE)
    matches = list(heading_pattern.finditer(wikitext))
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(wikitext)
        yield match.group(1).strip(), wikitext[start:end]


def iter_wiki_table_rows(section_text: str) -> Iterable[list[str]]:
    for table_match in re.finditer(r"\{\|.*?\n\|\}", section_text, re.DOTALL):
        table = table_match.group(0)
        for row_text in re.split(r"(?m)^\|-[^\n]*(?:\n|$)", table)[1:]:
            cells: list[str] = []
            for line in row_text.splitlines():
                if line.startswith("|}"):
                    break
                if line.startswith("!") or not line:
                    continue
                if line.startswith("|"):
                    cells.append(line[1:].strip().rstrip("|").strip())
                elif cells:
                    cells[-1] = f"{cells[-1]}\n{line.strip()}"

            if cells:
                yield cells


def extract_item_names(value: str) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    for match in re.finditer(r"\{\{\s*item\s*\|([^{}]+)\}\}", value, re.IGNORECASE):
        parts = [part.strip() for part in match.group(1).split("|") if part.strip()]
        raw_item_name = clean_wiki_text(parts[-1] if parts else "")
        item_name = WOWWIKI_ITEM_NAME_FIXES.get(raw_item_name, raw_item_name)
        if item_name and item_name not in seen:
            names.append(item_name)
            seen.add(item_name)
    return names


def clean_wiki_text(value: str) -> str:
    value = re.sub(r"\[\[[^|\]]+\|([^\]]+)\]\]", r"\1", value)
    value = re.sub(r"\[\[([^\]]+)\]\]", r"\1", value)
    value = re.sub(r"\{\{[^{}]*\}\}", "", value)
    value = value.replace("&nbsp;", " ")
    value = re.sub(r"'{2,}", "", value)
    value = re.sub(r"\s+", " ", value)
    return value.strip().strip("|").strip()


def clean_skill(value: str) -> str:
    match = re.search(r"\d+", clean_wiki_text(value))
    return match.group(0) if match else ""


def nonempty(value: object) -> object | None:
    return value if value not in ("", None) else None


def without_none(data: dict[str, object]) -> dict[str, object]:
    return {key: value for key, value in data.items() if value is not None}


def to_lua(value: object, indent: int = 0) -> str:
    if isinstance(value, dict):
        if not value:
            return "{}"
        pieces = ["{"]
        for key, child in value.items():
            pieces.append(
                f"{' ' * (indent + 2)}[{to_lua(str(key))}] = {to_lua(child, indent + 2)},"
            )
        pieces.append(f"{' ' * indent}" + "}")
        return "\n".join(pieces)

    if isinstance(value, list):
        if not value:
            return "{}"
        pieces = ["{"]
        for child in value:
            pieces.append(f"{' ' * (indent + 2)}{to_lua(child, indent + 2)},")
        pieces.append(f"{' ' * indent}" + "}")
        return "\n".join(pieces)

    if isinstance(value, str):
        return json.dumps(value)

    if isinstance(value, bool):
        return "true" if value else "false"

    if value is None:
        return "nil"

    return str(value)


def csv_args(paths: list[Path] | None) -> list[Path]:
    return paths if paths else [DEFAULT_GENERATED_CSV, DEFAULT_MANUAL_CSV]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    extract_parser = subparsers.add_parser(
        "extract-wowwiki",
        help="Extract CSV rows from a saved WowWiki parse response.",
    )
    extract_parser.add_argument("--input", type=Path, default=DEFAULT_WOWWIKI)
    extract_parser.add_argument("--out", type=Path, default=DEFAULT_GENERATED_CSV)
    extract_parser.add_argument("--fish-dir", type=Path, default=DEFAULT_FISH_DIR)
    extract_parser.add_argument("--zone-dir", type=Path, default=DEFAULT_ZONE_DIR)
    extract_parser.set_defaults(func=extract_wowwiki)

    export_json_parser = subparsers.add_parser("export-json", help="Export CSV data to JSON.")
    export_json_parser.add_argument("--csv", type=Path, action="append")
    export_json_parser.add_argument("--out", type=Path, default=DEFAULT_JSON)
    export_json_parser.set_defaults(func=lambda args: export_json(with_csv_args(args)))

    export_lua_parser = subparsers.add_parser("export-lua", help="Export CSV data to a Lua table.")
    export_lua_parser.add_argument("--csv", type=Path, action="append")
    export_lua_parser.add_argument("--out", type=Path, default=DEFAULT_LUA)
    export_lua_parser.add_argument("--global-name", default="ExtremeAnglinAtlasData")
    export_lua_parser.set_defaults(func=lambda args: export_lua(with_csv_args(args)))

    return parser


def with_csv_args(args: argparse.Namespace) -> argparse.Namespace:
    args.csv = csv_args(args.csv)
    return args


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        args.func(args)
    except DataError as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
